"use client";

import { createContext, useContext, useEffect, useMemo, useState } from "react";

const STORAGE_KEY = "site-language";

const translations = {
  fa: {
    siteName: "زارعون",
    siteTagline: "زارعون بستری امن میان تولید و مصرف",
    siteIntro: "زارعون، بازار آنلاین خرید و فروش انواع محصولات؛ ارتباط مستقیم میان تولیدکننده، تامین‌کننده و خریدار.",
    cart: "سبد خرید",
    dashboard: "داشبورد",
    loginRegister: "ورود / ثبت نام",
    logout: "خروج",
    account: "حساب کاربری",
    allRightsReserved: "تمامی حقوق این سایت برای زارعون محفوظ است",
    home: "خانه",
    search: "جستجو",
    products: "محصولات",
    inventory: "موجودی",
    orders: "سفارشات",
    login: "ورود",
    profile: "پروفایل",
    searchPlaceholder: "جست‌وجو در محصولات و دسته‌ها...",
    productsAvailable: "محصولات موجود",
    showAllCategories: "همه دسته‌ها",
    nothingFound: "چیزی یافت نشد",
    product: "محصول",
    category: "دسته",
    totalAvailableStock: "مجموع موجودی",
    supplySource: "منبع عرضه",
    supplyCountry: "کشور عرضه",
    supplyCity: "شهر (اختیاری)",
    noProductsWithStock: "محصولی با موجودی ثبت نشده است.",
    viewAllCategories: "مشاهده همه دسته‌ها",
    adBadge: "خدمات بازرسی و کنترل کیفیت",
    adSponsoredLabel: "تبلیغات",
    adBrandName: "آریا فولاد قرن",
    openAdDetails: "مشاهده تبلیغ",
    adTitle: "قبل از واردات یا صادرات، از کیفیت کالای خود مطمئن شوید.",
    adDescription:
      "آریا فولاد قرن با ارائه خدمات بازرسی کالا، کنترل کیفیت، بازرسی مواد اولیه، تجهیزات صنعتی و صدور گواهینامه‌های معتبر، ریسک معاملات تجاری شما را کاهش داده و از انطباق کالا با استانداردهای موردنیاز اطمینان حاصل می‌کند.",
    adItem1: "بازرسی کالاهای وارداتی و صادراتی",
    adItem2: "کنترل کیفیت (QC)",
    adItem3: "بازرسی مواد اولیه و محصولات تولیدی",
    adItem4: "گزارش فنی و صدور گواهینامه بازرسی",
    adFooter: "شرکت بازرسی مهندسی آریا فولاد قرن؛ همراه مطمئن تجارت بین‌المللی شما.",
    enterSite: "برای ورود به سایت کلیک کنید",
    lcBadge: "اعتبار اسنادی",
    openLcDetails: "مشاهده جزئیات",
    lcTitle: "خدمات تخصصی اعتبار اسنادی (LC)",
    lcDescription:
      "اگر برای واردات یا صادرات خود به LC نیاز دارید، تمامی مراحل افتتاح، پیگیری و اجرای آن را با اطمینان به ما بسپارید.",
    lcItem1: "افتتاح اعتبار اسنادی (LC)",
    lcItem2: "پیگیری مراحل اجرایی",
    lcItem3: "هماهنگی بانک و طرفین معامله",
    lcItem4: "مشاوره واردات و صادرات",
    lcFooter: "همراه مطمئن شما در تجارت بین‌المللی.",
    lcRequestCta: "درخواست LC",
    lcFormTitle: "فرم درخواست اعتبار اسنادی (LC)",
    lcFormFullName: "نام و نام خانوادگی",
    lcFormPhone: "شماره تماس",
    lcFormEmail: "ایمیل",
    lcFormCompany: "نام شرکت",
    lcFormTradeType: "نوع معامله",
    lcFormTradeImport: "واردات",
    lcFormTradeExport: "صادرات",
    lcFormTradeBoth: "واردات و صادرات",
    lcFormProductDescription: "شرح کالا / خدمات",
    lcFormEstimatedAmount: "مبلغ تقریبی",
    lcFormCurrency: "ارز",
    lcFormBankName: "نام بانک (در صورت وجود)",
    lcFormNotes: "توضیحات تکمیلی",
    lcFormRequiredError: "نام و شماره تماس الزامی است",
    lcFormSubmitError: "خطا در ارسال درخواست. لطفاً دوباره تلاش کنید.",
    lcFormSubmitting: "در حال ارسال...",
    lcFormSuccessTitle: "درخواست شما ثبت شد",
    lcFormSuccessMessage: "کارشناسان زارعون در اسرع وقت با شما تماس خواهند گرفت.",
    agriculturalProducts: "محصولات کشاورزی",
    agriculturalProductsDesc: "مجموعه کاملی از محصولات کشاورزی، نهاده‌ها و تجهیزات مورد نیاز شما",
    productCategories: "دسته‌بندی محصولات",
    subcategoriesAndProducts: "زیردسته‌ها و محصولات",
    viewAll: "مشاهده همه",
    noItemsRegistered: "موردی ثبت نشده",
    noCategoryRegistered: "دسته‌بندی‌ای ثبت نشده است.",
    pleaseVisitLater: "لطفاً بعداً مراجعه کنید.",
    requestedItemsInCart: "درخواست داده شده - {count} آیتم در بار شما موجود است",
    viewCartAndSubmit: "مشاهده بار و ثبت بار",
    cartReservationNote: "با زدن ثبت بار، بار رزرو نمی‌شود ولی با مشتری تماس گرفته می‌شود جهت رزرو شدن بار.",
    supportContact: "تماس پشتیبانی",
    pleaseLoginFirst: "ابتدا وارد شوید",
    statusOnField: "در مزرعه",
    statusHarvested: "برداشت‌شده",
    statusReserved: "رزرو شده",
    statusSold: "فروخته شده",
    qualityExport: "صادراتی",
    qualityGrade1: "درجه 1",
    qualityGrade2: "درجه 2",
    qualityGrade3: "درجه 3",
    qualityWaste: "ضایعاتی",
    qualityOther: "سایر",
    mainPage: "صفحه اصلی",
    orderable: "قابل سفارش",
    unitLabel: "واحد",
    nonOrderableCategoryRole: "غیرقابل سفارش (نقش دسته)",
    totalStockStatus: "وضعیت موجودی کل",
    totalStock: "کل موجودی",
    totalProducts: "تعداد محصولات",
    productsWithStock: "محصولات دارای موجودی",
    inventoryStatus: "وضعیت موجودی",
    reserved: "رزرو شده",
    availableToOffer: "قابل عرضه",
    grade: "درجه",
    total: "کل",
    lotsCount: "تعداد بار",
    availableProductsTitle: "محصولات موجود",
    media: "رسانه",
    price: "قیمت",
    minimumOrder: "حداقل سفارش",
    status: "وضعیت",
    attributes: "ویژگی‌ها",
    supplier: "تامین‌کننده",
    request: "درخواست",
    steppedPricing: "قیمت پلکانی",
    notSet: "—",
    fixedPrice: "قیمت ثابت",
    priceNotSet: "قیمت تعیین نشده",
    currencyToman: "تومان",
    moreAttributes: "+{count} ویژگی دیگر",
    orderRequest: "درخواست سفارش",
    invalidQuantity: "مقدار نامعتبر است",
    order: "سفارش",
    loading: "در حال بارگذاری...",
    noMediaToShow: "موردی برای نمایش وجود ندارد.",
    images: "تصاویر",
    videos: "ویدیوها",
    productMedia: "رسانه‌های محصول",
    productLabelPlural: "محصولات",
    view: "مشاهده",
    youHaveInCart: "شما هم‌اکنون {quantity} {unit} از این محصول را در سبد دارید.",
    viewCart: "مشاهده سبد خرید",
    orderAdded: "به بار اضافه شد.",
    closeMenu: "بستن منو",
    stockLegendAriaLabel: "راهنمای رنگ موجودی",
    catalogGuidePanelAriaLabel: "راهنمای دسته و محصول و رنگ کارت‌ها",
    stockLegendShortTitle: "رنگ‌بندی کارت‌ها",
    openGuideHelp: "مشاهده راهنما",
    closeGuide: "بستن",
    stockLegendTitle: "رنگ کارت‌ها بر اساس میزان موجودی (کیلوگرم) است:",
    stockEmpty: "بدون موجودی",
    stockEmptyRange: "۰ کیلوگرم",
    stockLow: "موجودی کم",
    stockLowRange: "زیر ۵ تن",
    stockMedium: "موجودی متوسط",
    stockMediumRange: "۵ تا ۲۰ تن",
    stockHigh: "موجودی زیاد",
    stockHighRange: "بالای ۲۰ تن",
    categoryProductGuideTitle: "تفاوت دسته و محصول",
    categoryProductGuideIntro: "کنار هر مورد در کارت‌ها، یکی از این دو برچسب نمایش داده می‌شود:",
    categoryProductGuideCategory:
      "گروهی که هنوز زیرمجموعه یا انواع بیشتری دارد و برای انتخاب کالای نهایی باید مرحلهٔ بعد را باز کنید.",
    categoryProductGuideProduct:
      "کالای نهایی و قابل سفارش؛ می‌توانید مستقیماً از صفحهٔ همان مورد درخواست خود را ثبت کنید.",
  },
  en: {
    siteName: "Zareoon",
    siteTagline: "A trusted bridge between production and consumption",
    siteIntro: "Zareoon is an online marketplace for various products, connecting producers, suppliers, and buyers directly.",
    cart: "Cart",
    dashboard: "Dashboard",
    loginRegister: "Login / Register",
    logout: "Logout",
    account: "Account",
    allRightsReserved: "All rights reserved for Zareoon",
    home: "Home",
    search: "Search",
    products: "Products",
    inventory: "Inventory",
    orders: "Orders",
    login: "Login",
    profile: "Profile",
    searchPlaceholder: "Search products and categories...",
    productsAvailable: "Available Products",
    showAllCategories: "All Categories",
    nothingFound: "Nothing found",
    product: "Product",
    category: "Category",
    totalAvailableStock: "Total available",
    supplySource: "Supply source",
    supplyCountry: "Supply country",
    supplyCity: "City (optional)",
    noProductsWithStock: "No products with registered stock.",
    viewAllCategories: "View all categories",
    adBadge: "Inspection & Quality Control",
    adSponsoredLabel: "Advertisement",
    adBrandName: "Arya Foolad Gharn",
    openAdDetails: "View advertisement",
    adTitle: "Make sure of your goods quality before import or export.",
    adDescription:
      "Arya Foolad Gharn reduces your trade risks and ensures compliance with required standards through cargo inspection, quality control, raw material inspection, industrial equipment inspection, and valid certification services.",
    adItem1: "Imported and exported goods inspection",
    adItem2: "Quality control (QC)",
    adItem3: "Raw materials and production inspection",
    adItem4: "Technical reports and inspection certificates",
    adFooter: "Arya Foolad Gharn Engineering Inspection Company; your trusted partner in international trade.",
    enterSite: "Click to visit website",
    lcBadge: "Letter of Credit",
    openLcDetails: "View details",
    lcTitle: "Specialized Letter of Credit (LC) Services",
    lcDescription:
      "If you need an LC for import or export, entrust us with every stage of opening, tracking, and executing it with confidence.",
    lcItem1: "LC opening",
    lcItem2: "Process tracking",
    lcItem3: "Bank and counterparty coordination",
    lcItem4: "Import and export advisory",
    lcFooter: "Your trusted partner in international trade.",
    lcRequestCta: "Request LC",
    lcFormTitle: "Letter of Credit (LC) Request Form",
    lcFormFullName: "Full name",
    lcFormPhone: "Phone number",
    lcFormEmail: "Email",
    lcFormCompany: "Company name",
    lcFormTradeType: "Trade type",
    lcFormTradeImport: "Import",
    lcFormTradeExport: "Export",
    lcFormTradeBoth: "Import and export",
    lcFormProductDescription: "Goods / services description",
    lcFormEstimatedAmount: "Estimated amount",
    lcFormCurrency: "Currency",
    lcFormBankName: "Bank name (if any)",
    lcFormNotes: "Additional notes",
    lcFormRequiredError: "Full name and phone are required",
    lcFormSubmitError: "Failed to submit request. Please try again.",
    lcFormSubmitting: "Submitting...",
    lcFormSuccessTitle: "Your request has been submitted",
    lcFormSuccessMessage: "Zareoon specialists will contact you as soon as possible.",
    agriculturalProducts: "Agricultural Products",
    agriculturalProductsDesc: "A complete range of agricultural products, inputs, and equipment you need",
    productCategories: "Product Categories",
    subcategoriesAndProducts: "Subcategories and products",
    viewAll: "View all",
    noItemsRegistered: "No items registered",
    noCategoryRegistered: "No categories have been registered.",
    pleaseVisitLater: "Please check back later.",
    requestedItemsInCart: "Request submitted - {count} items are currently in your cargo list",
    viewCartAndSubmit: "View cargo and submit",
    cartReservationNote: "Submitting cargo does not reserve it, but our team will contact the customer to complete the reservation.",
    supportContact: "Support",
    pleaseLoginFirst: "Please log in first",
    statusOnField: "On field",
    statusHarvested: "Harvested",
    statusReserved: "Reserved",
    statusSold: "Sold",
    qualityExport: "Export",
    qualityGrade1: "Grade 1",
    qualityGrade2: "Grade 2",
    qualityGrade3: "Grade 3",
    qualityWaste: "Waste",
    qualityOther: "Other",
    mainPage: "Home",
    orderable: "Orderable",
    unitLabel: "Unit",
    nonOrderableCategoryRole: "Not orderable (category role)",
    totalStockStatus: "Overall stock status",
    totalStock: "Total stock",
    totalProducts: "Products count",
    productsWithStock: "Products with stock",
    inventoryStatus: "Stock status",
    reserved: "Reserved",
    availableToOffer: "Available",
    grade: "Grade",
    total: "Total",
    lotsCount: "Lots",
    availableProductsTitle: "Available Lots",
    media: "Media",
    price: "Price",
    minimumOrder: "Minimum order",
    status: "Status",
    attributes: "Attributes",
    supplier: "Supplier",
    request: "Request",
    steppedPricing: "Tiered pricing",
    notSet: "—",
    fixedPrice: "Fixed price",
    priceNotSet: "Price not set",
    currencyToman: "Toman",
    moreAttributes: "+{count} more attributes",
    orderRequest: "Order request",
    invalidQuantity: "Invalid quantity",
    order: "Order",
    loading: "Loading...",
    noMediaToShow: "There is no media to display.",
    images: "Images",
    videos: "Videos",
    productMedia: "Product media",
    productLabelPlural: "Products",
    view: "View",
    youHaveInCart: "You currently have {quantity} {unit} of this product in your cart.",
    viewCart: "View cart",
    orderAdded: "Added to cargo list.",
    closeMenu: "Close menu",
    stockLegendAriaLabel: "Stock color guide",
    catalogGuidePanelAriaLabel: "Category, product and card color guide",
    stockLegendShortTitle: "Card colors",
    openGuideHelp: "View guide",
    closeGuide: "Close",
    stockLegendTitle: "Card colors are based on available stock (kilograms):",
    stockEmpty: "Out of stock",
    stockEmptyRange: "0 kg",
    stockLow: "Low stock",
    stockLowRange: "Below 5 tons",
    stockMedium: "Medium stock",
    stockMediumRange: "5 to 20 tons",
    stockHigh: "High stock",
    stockHighRange: "Above 20 tons",
    categoryProductGuideTitle: "Categories and products",
    categoryProductGuideIntro: "Each item in a card is marked with one of these labels:",
    categoryProductGuideCategory:
      "A group that still has subcategories or varieties — open the next level to reach the final item.",
    categoryProductGuideProduct:
      "The final orderable item — submit your request directly from that page.",
  },
  ru: {
    siteName: "Zareoon",
    siteTagline: "Надежная платформа между производством и потреблением",
    siteIntro: "Zareoon - онлайн-площадка для торговли различными товарами, связывающая производителей, поставщиков и покупателей.",
    cart: "Корзина",
    dashboard: "Панель",
    loginRegister: "Вход / Регистрация",
    logout: "Выход",
    account: "Аккаунт",
    allRightsReserved: "Все права на этот сайт принадлежат Zareoon",
    home: "Главная",
    search: "Поиск",
    products: "Товары",
    inventory: "Запасы",
    orders: "Заказы",
    login: "Вход",
    profile: "Профиль",
    searchPlaceholder: "Поиск товаров и категорий...",
    productsAvailable: "Товары в наличии",
    showAllCategories: "Все категории",
    nothingFound: "Ничего не найдено",
    product: "Товар",
    category: "Категория",
    totalAvailableStock: "Всего в наличии",
    supplySource: "Источник поставки",
    supplyCountry: "Страна поставки",
    supplyCity: "Город (необязательно)",
    noProductsWithStock: "Нет товаров с зарегистрированным наличием.",
    viewAllCategories: "Смотреть все категории",
    adBadge: "Инспекция и контроль качества",
    adSponsoredLabel: "Реклама",
    adBrandName: "Arya Foolad Gharn",
    openAdDetails: "Посмотреть рекламу",
    adTitle: "Убедитесь в качестве товара до импорта или экспорта.",
    adDescription:
      "Arya Foolad Gharn снижает риски ваших торговых сделок и обеспечивает соответствие стандартам, предоставляя инспекцию товаров, контроль качества, проверку сырья, промышленного оборудования и выдачу официальных сертификатов.",
    adItem1: "Инспекция импортных и экспортных грузов",
    adItem2: "Контроль качества (QC)",
    adItem3: "Проверка сырья и готовой продукции",
    adItem4: "Технические отчеты и сертификаты инспекции",
    adFooter: "Инженерно-инспекционная компания Arya Foolad Gharn — ваш надежный партнер в международной торговле.",
    enterSite: "Нажмите, чтобы перейти на сайт",
    lcBadge: "Аккредитив",
    openLcDetails: "Подробнее",
    lcTitle: "Специализированные услуги по аккредитиву (LC)",
    lcDescription:
      "Если вам нужен LC для импорта или экспорта, доверьте нам все этапы открытия, сопровождения и исполнения с полной уверенностью.",
    lcItem1: "Открытие аккредитива (LC)",
    lcItem2: "Сопровождение процесса",
    lcItem3: "Координация с банком и контрагентами",
    lcItem4: "Консультации по импорту и экспорту",
    lcFooter: "Ваш надежный партнер в международной торговле.",
    lcRequestCta: "Запрос LC",
    lcFormTitle: "Форма запроса аккредитива (LC)",
    lcFormFullName: "ФИО",
    lcFormPhone: "Телефон",
    lcFormEmail: "Email",
    lcFormCompany: "Название компании",
    lcFormTradeType: "Тип сделки",
    lcFormTradeImport: "Импорт",
    lcFormTradeExport: "Экспорт",
    lcFormTradeBoth: "Импорт и экспорт",
    lcFormProductDescription: "Описание товара / услуги",
    lcFormEstimatedAmount: "Примерная сумма",
    lcFormCurrency: "Валюта",
    lcFormBankName: "Банк (если есть)",
    lcFormNotes: "Дополнительные примечания",
    lcFormRequiredError: "Укажите имя и телефон",
    lcFormSubmitError: "Не удалось отправить запрос. Попробуйте снова.",
    lcFormSubmitting: "Отправка...",
    lcFormSuccessTitle: "Запрос отправлен",
    lcFormSuccessMessage: "Специалисты Zareoon свяжутся с вами в ближайшее время.",
    agriculturalProducts: "Сельскохозяйственная продукция",
    agriculturalProductsDesc: "Полный набор сельскохозяйственной продукции, материалов и оборудования",
    productCategories: "Категории товаров",
    subcategoriesAndProducts: "Подкатегории и товары",
    viewAll: "Смотреть все",
    noItemsRegistered: "Ничего не зарегистрировано",
    noCategoryRegistered: "Категории не зарегистрированы.",
    pleaseVisitLater: "Пожалуйста, зайдите позже.",
    requestedItemsInCart: "Запрос отправлен — {count} позиций сейчас находятся в вашем списке груза",
    viewCartAndSubmit: "Открыть груз и отправить",
    cartReservationNote: "Отправка груза не резервирует его автоматически, но с клиентом свяжутся для подтверждения резерва.",
    supportContact: "Поддержка",
    pleaseLoginFirst: "Сначала войдите",
    statusOnField: "В поле",
    statusHarvested: "Собрано",
    statusReserved: "Зарезервировано",
    statusSold: "Продано",
    qualityExport: "Экспорт",
    qualityGrade1: "1 сорт",
    qualityGrade2: "2 сорт",
    qualityGrade3: "3 сорт",
    qualityWaste: "Отходы",
    qualityOther: "Другое",
    mainPage: "Главная",
    orderable: "Можно заказать",
    unitLabel: "Ед.",
    nonOrderableCategoryRole: "Недоступно для заказа (категория)",
    totalStockStatus: "Общее состояние запасов",
    totalStock: "Общий запас",
    totalProducts: "Количество товаров",
    productsWithStock: "Товары в наличии",
    inventoryStatus: "Состояние запасов",
    reserved: "Зарезервировано",
    availableToOffer: "Доступно",
    grade: "Сорт",
    total: "Всего",
    lotsCount: "Партии",
    availableProductsTitle: "Доступные партии",
    media: "Медиа",
    price: "Цена",
    minimumOrder: "Мин. заказ",
    status: "Статус",
    attributes: "Характеристики",
    supplier: "Поставщик",
    request: "Запрос",
    steppedPricing: "Ступенчатая цена",
    notSet: "—",
    fixedPrice: "Фиксированная цена",
    priceNotSet: "Цена не указана",
    currencyToman: "Томан",
    moreAttributes: "+{count} атрибутов",
    orderRequest: "Запрос заказа",
    invalidQuantity: "Неверное количество",
    order: "Заказать",
    loading: "Загрузка...",
    noMediaToShow: "Нет медиа для отображения.",
    images: "Изображения",
    videos: "Видео",
    productMedia: "Медиа товара",
    productLabelPlural: "Товары",
    view: "Открыть",
    youHaveInCart: "Сейчас у вас в корзине {quantity} {unit} этого товара.",
    viewCart: "Открыть корзину",
    orderAdded: "Добавлено в список груза.",
    closeMenu: "Закрыть меню",
    stockLegendAriaLabel: "Справочник цветов запасов",
    catalogGuidePanelAriaLabel: "Справочник категорий, товаров и цветов карточек",
    stockLegendShortTitle: "Цвета карточек",
    openGuideHelp: "Открыть справочник",
    closeGuide: "Закрыть",
    stockLegendTitle: "Цвет карточек зависит от доступного запаса (в килограммах):",
    stockEmpty: "Нет в наличии",
    stockEmptyRange: "0 кг",
    stockLow: "Низкий запас",
    stockLowRange: "Менее 5 тонн",
    stockMedium: "Средний запас",
    stockMediumRange: "От 5 до 20 тонн",
    stockHigh: "Высокий запас",
    stockHighRange: "Более 20 тонн",
    categoryProductGuideTitle: "Категория и товар",
    categoryProductGuideIntro: "Рядом с каждым пунктом в карточке указана одна из этих меток:",
    categoryProductGuideCategory:
      "Группа с подкатегориями или разными видами — откройте следующий уровень, чтобы выбрать конечный товар.",
    categoryProductGuideProduct:
      "Конечный товар, доступный для заказа — оформите запрос прямо на его странице.",
  },
};

const siteIntroByLang = {
  fa: translations.fa.siteIntro,
  en: translations.en.siteIntro,
  ru: translations.ru.siteIntro,
};

export { siteIntroByLang };

const LanguageContext = createContext(null);

function interpolate(template, values = {}) {
  return Object.entries(values).reduce(
    (acc, [key, value]) => acc.replaceAll(`{${key}}`, value),
    template
  );
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState("fa");
  const [isHydrated, setIsHydrated] = useState(false);

  useEffect(() => {
    const saved = window.localStorage.getItem(STORAGE_KEY);
    if (saved && ["fa", "en", "ru"].includes(saved)) {
      setLanguage(saved);
    } else if (saved === "ar") {
      setLanguage("fa");
    }
    setIsHydrated(true);
  }, []);

  useEffect(() => {
    if (!isHydrated) return;
    window.localStorage.setItem(STORAGE_KEY, language);
    document.documentElement.lang = language;
    document.documentElement.dir = language === "fa" ? "rtl" : "ltr";
  }, [language, isHydrated]);

  const value = useMemo(() => {
    const dict = translations[language] && Object.keys(translations[language]).length
      ? translations[language]
      : translations.fa;
    return {
      language,
      setLanguage,
      isHydrated,
      isRTL: language === "fa",
      t: (key, values) => {
        const text = dict[key] ?? translations.fa[key] ?? key;
        return values ? interpolate(text, values) : text;
      },
      siteIntroByLang,
    };
  }, [language, isHydrated]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}
