"use client";

import { createContext, useContext, useEffect, useMemo, useState } from "react";

const STORAGE_KEY = "site-language";

const translations = {
  fa: {
    siteName: "زارعون",
    siteTagline: "زارعون بستری امن میان تولید و مصرف",
    siteIntro: "زارعون، بازار آنلاین خرید و فروش انواع محصولات؛ ارتباط مستقیم میان تولیدکننده، تامین‌کننده و خریدار.",
    cart: "سبد خرید",
    language: "زبان",
    selectLanguage: "انتخاب زبان",
    dashboard: "داشبورد",
    loginRegister: "ورود / ثبت نام",
    logout: "خروج",
    account: "حساب کاربری",
    zareoonMe: "زارعون من",
    myPublicPage: "صفحه عمومی من",
    myProducts: "محصولات من",
    addProduct: "ثبت محصول",
    addNewProduct: "ثبت محصول جدید",
    editProfile: "ویرایش پروفایل",
    customerOrders: "سفارشات مشتری",
    accountPageSubtitle: "مشخصات شخصی، تماس و امنیت حساب خود را مدیریت کنید.",
    firstName: "نام",
    lastName: "نام خانوادگی",
    fatherName: "نام پدر",
    nationalId: "شماره شناسنامه",
    address: "آدرس",
    postalCode: "کد پستی",
    email: "ایمیل",
    mobile: "موبایل",
    phone: "تلفن",
    currentPassword: "رمز عبور فعلی",
    newPassword: "رمز عبور جدید",
    confirmPassword: "تکرار رمز عبور جدید",
    saveChanges: "ذخیره تغییرات",
    saving: "در حال ذخیره...",
    profileUpdated: "اطلاعات با موفقیت ذخیره شد.",
    profileUpdateFailed: "خطا در ذخیره اطلاعات.",
    personalInfo: "اطلاعات شخصی",
    contactInfo: "اطلاعات تماس",
    security: "امنیت حساب",
    changePasswordHint: "برای تغییر رمز عبور، فیلدهای زیر را پر کنید؛ در غیر این صورت خالی بگذارید.",
    readOnlyField: "غیرقابل ویرایش",
    changePhoto: "تغییر تصویر",
    removePhoto: "حذف تصویر",
    uploadingPhoto: "در حال آپلود...",
    photoUploadSuccess: "تصویر پروفایل ذخیره شد.",
    photoUploadFailed: "خطا در آپلود تصویر.",
    photoRemoveSuccess: "تصویر پروفایل حذف شد.",
    photoHint: "PNG، JPG یا WEBP — حداکثر ۱۰ مگابایت",
    changePassword: "تغییر رمز عبور",
    accountTabDocuments: "مدارک",
    accountTabMyFiles: "فایل‌های من",
    accountDocumentsHint: "مدارک شناسایی و اسناد موردنیاز را بارگذاری کنید.",
    noFilesUploaded: "هنوز فایلی آپلود نکرده‌اید.",
    download: "دانلود",
    allRightsReserved: "تمامی حقوق این سایت برای زارعون محفوظ است",
    home: "خانه",
    search: "جستجو",
    products: "محصولات",
    inventory: "موجودی",
    orders: "سفارشات",
    login: "ورود",
    profile: "پروفایل",
    searchPlaceholder: "جست‌وجو در محصولات و دسته‌ها...",
    productsAvailable: "محصولات موجود",
    latestAvailableOnZareoon: "جدیدترین محصولات موجود در زارعون",
    latestAvailableInCategory: "جدیدترین محصولات موجود در این دسته",
    latestAvailableInParent: "جدیدترین محصولات موجود در {name}",
    latestAvailableShort: "جدیدترین موجود",
    showAllCategories: "همه دسته‌ها",
    browseByCategory: "مرور دسته‌ها",
    browseByCategoryHint: "یکی از دسته‌های بالا را انتخاب کنید تا زیردسته‌ها و محصولات را مرحله‌به‌مرحله ببینید.",
    nothingFound: "چیزی یافت نشد",
    product: "محصول",
    category: "دسته",
    totalAvailableStock: "مجموع موجودی",
    supplySource: "منبع عرضه",
    supplyCountry: "کشور عرضه",
    supplyCity: "شهر (اختیاری)",
    noProductsWithStock: "محصولی با موجودی ثبت نشده است.",
    viewAllCategories: "مشاهده همه دسته‌ها",
    adBadge: "خدمات بازرسی و کنترل کیفیت",
    adSponsoredLabel: "تبلیغات",
    adBrandName: "آریا فولاد قرن",
    openAdDetails: "مشاهده تبلیغ",
    adTitle: "قبل از واردات یا صادرات، از کیفیت کالای خود مطمئن شوید.",
    adDescription:
      "آریا فولاد قرن با ارائه خدمات بازرسی کالا، کنترل کیفیت، بازرسی مواد اولیه، تجهیزات صنعتی و صدور گواهینامه‌های معتبر، ریسک معاملات تجاری شما را کاهش داده و از انطباق کالا با استانداردهای موردنیاز اطمینان حاصل می‌کند.",
    adItem1: "بازرسی کالاهای وارداتی و صادراتی",
    adItem2: "کنترل کیفیت (QC)",
    adItem3: "بازرسی مواد اولیه و محصولات تولیدی",
    adItem4: "گزارش فنی و صدور گواهینامه بازرسی",
    adFooter: "شرکت بازرسی مهندسی آریا فولاد قرن؛ همراه مطمئن تجارت بین‌المللی شما.",
    enterSite: "برای ورود به سایت کلیک کنید",
    lcBadge: "اعتبار اسنادی",
    openLcDetails: "مشاهده جزئیات",
    lcTitle: "خدمات تخصصی اعتبار اسنادی (LC)",
    lcDescription:
      "اگر برای واردات یا صادرات خود به LC نیاز دارید، تمامی مراحل افتتاح، پیگیری و اجرای آن را با اطمینان به ما بسپارید.",
    lcItem1: "افتتاح اعتبار اسنادی (LC)",
    lcItem2: "پیگیری مراحل اجرایی",
    lcItem3: "هماهنگی بانک و طرفین معامله",
    lcItem4: "مشاوره واردات و صادرات",
    lcFooter: "همراه مطمئن شما در تجارت بین‌المللی.",
    lcRequestCta: "درخواست LC",
    lcFormTitle: "فرم درخواست اعتبار اسنادی (LC)",
    lcFormFullName: "نام و نام خانوادگی",
    lcFormPhone: "شماره تماس",
    lcFormEmail: "ایمیل",
    lcFormCompany: "نام شرکت",
    lcFormTradeType: "نوع معامله",
    lcFormTradeImport: "واردات",
    lcFormTradeExport: "صادرات",
    lcFormTradeBoth: "واردات و صادرات",
    lcFormProductDescription: "شرح کالا / خدمات",
    lcFormEstimatedAmount: "مبلغ تقریبی",
    lcFormCurrency: "ارز",
    lcFormBankName: "نام بانک (در صورت وجود)",
    lcFormNotes: "توضیحات تکمیلی",
    lcFormRequiredError: "نام و شماره تماس الزامی است",
    lcFormSubmitError: "خطا در ارسال درخواست. لطفاً دوباره تلاش کنید.",
    lcFormSubmitting: "در حال ارسال...",
    lcFormSuccessTitle: "درخواست شما ثبت شد",
    lcFormSuccessMessage: "کارشناسان زارعون در اسرع وقت با شما تماس خواهند گرفت.",
    serviceRequestCta: "ثبت درخواست",
    serviceRequestFormTitle: "فرم درخواست {service}",
    srFormOriginCountry: "کشور مبدأ",
    srFormDestinationCountry: "کشور مقصد",
    srFormIncoterm: "اینکوترمز",
    srFormTransportMode: "روش حمل",
    srFormTransportSea: "دریایی",
    srFormTransportAir: "هوایی",
    srFormTransportRoad: "زمینی",
    srFormTransportRail: "ریلی",
    srFormOriginLocation: "مبدأ حمل",
    srFormDestinationLocation: "مقصد حمل",
    srFormCargoWeight: "وزن / حجم محموله",
    srFormPortOfEntry: "گمرک / بندر ورود",
    srFormHsCode: "کد تعرفه (HS)",
    srFormDeclarationType: "نوع اظهارنامه",
    srFormPaymentMethod: "روش پرداخت",
    srFormPaymentLc: "اعتبار اسنادی (LC)",
    srFormPaymentTt: "حواله ارزی (TT)",
    srFormPaymentCollection: "وصول اسنادی",
    srFormPaymentOther: "سایر",
    srFormBankName: "نام بانک",
    srFormInspectionType: "نوع بازرسی",
    srFormStandardRequired: "استاندارد موردنیاز",
    srFormInspectionLocation: "محل بازرسی",
    srFormInsuranceCoverage: "نوع پوشش بیمه",
    srFormCargoValue: "ارزش محموله",
    srFormRouteDescription: "مسیر حمل",
    srFormTargetMarket: "بازار هدف",
    srFormConsultationTopic: "موضوع مشاوره",
    srFormRequiredDocuments: "اسناد موردنیاز",
    srFormShipmentDeadline: "مهلت ارسال",
    serviceRequestCta: "ثبت درخواست",
    serviceRequestFormTitle: "فرم درخواست — {service}",
    srFormOriginCountry: "کشور مبدأ",
    srFormDestinationCountry: "کشور مقصد",
    srFormIncoterm: "اینکوترمز",
    srFormTransportMode: "روش حمل",
    srFormTransportSea: "دریایی",
    srFormTransportAir: "هوایی",
    srFormTransportRoad: "زمینی",
    srFormTransportRail: "ریلی",
    srFormOriginLocation: "مبدأ حمل",
    srFormDestinationLocation: "مقصد حمل",
    srFormCargoWeight: "وزن / حجم محموله",
    srFormPortOfEntry: "گمرک / بندر ورود",
    srFormHsCode: "کد تعرفه (HS)",
    srFormDeclarationType: "نوع اظهارنامه",
    srFormPaymentMethod: "روش پرداخت",
    srFormPaymentLc: "اعتبار اسنادی (LC)",
    srFormPaymentTt: "حواله ارزی (TT)",
    srFormPaymentCollection: "وصول اسنادی",
    srFormPaymentOther: "سایر",
    srFormBankName: "نام بانک",
    srFormInspectionType: "نوع بازرسی",
    srFormStandardRequired: "استاندارد موردنیاز",
    srFormInspectionLocation: "محل بازرسی",
    srFormInsuranceCoverage: "نوع پوشش بیمه",
    srFormCargoValue: "ارزش محموله",
    srFormRouteDescription: "مسیر حمل",
    srFormTargetMarket: "بازار هدف",
    srFormConsultationTopic: "موضوع مشاوره",
    srFormRequiredDocuments: "اسناد موردنیاز",
    srFormShipmentDeadline: "مهلت ارسال",
    agriculturalProducts: "محصولات و دسته‌بندی‌ها",
    agriculturalProductsDesc: "مجموعه کاملی از محصولات، کالاها و خدمات از تأمین‌کنندگان مختلف",
    downloadCatalogPdf: "دانلود PDF کاتالوگ",
    downloadSupplierCatalogPdf: "دانلود کاتالوگ این تامین‌کننده",
    productCategories: "دسته‌بندی محصولات",
    categoriesShort: "دسته‌بندی",
    back: "بازگشت",
    subcategoriesAndProducts: "زیردسته‌ها و محصولات",
    subcategories: "زیردسته‌ها",
    subcategoriesOfParent: "زیردسته‌های {name}",
    showOnlyWithStock: "فقط دارای موجودی",
    groupByCategory: "تفکیک دسته‌ها",
    viewAll: "مشاهده همه",
    noItemsRegistered: "موردی ثبت نشده",
    noCategoryRegistered: "دسته‌بندی‌ای ثبت نشده است.",
    pleaseVisitLater: "لطفاً بعداً مراجعه کنید.",
    requestedItemsInCart: "درخواست ثبت شده — {count} قلم در سبد خرید شماست",
    viewCartAndSubmit: "مشاهده سبد و نهایی کردن سفارش",
    cartReservationNote: "نهایی کردن سفارش به‌معنای رزرو خودکار موجودی نیست؛ پس از ثبت، تیم زارعون برای تأیید و هماهنگی تحویل با شما تماس می‌گیرد.",
    supportContact: "تماس پشتیبانی",
    pleaseLoginFirst: "ابتدا وارد شوید",
    statusOnField: "در محل تأمین",
    statusHarvested: "قابل عرضه",
    statusReserved: "رزرو شده",
    statusSold: "فروخته شده",
    qualityExport: "صادراتی",
    qualityGrade1: "درجه 1",
    qualityGrade2: "درجه 2",
    qualityGrade3: "درجه 3",
    qualityWaste: "ضایعاتی",
    qualityOther: "سایر",
    mainPage: "صفحه اصلی",
    orderable: "قابل سفارش",
    unitLabel: "واحد",
    nonOrderableCategoryRole: "غیرقابل سفارش (نقش دسته)",
    totalStockStatus: "وضعیت موجودی کل",
    totalStock: "کل موجودی",
    totalProducts: "تعداد محصولات",
    productsWithStock: "محصولات دارای موجودی",
    inventoryStatus: "وضعیت موجودی",
    inventoryOverviewDesc: "مجموع موجودی این محصول و مقداری که می‌توانید سفارش دهید",
    inventoryOverviewShort: "جزئیات هر درجه در بخش پیشنهادها",
    gradeBreakdownTitle: "موجودی به تفکیک درجه",
    gradeBreakdownDesc: "مقایسه موجودی هر درجه کیفیت",
    offersSectionTitle: "پیشنهادهای قابل سفارش",
    offersSectionDesc: "مقدار را وارد کنید و به سبد خرید اضافه کنید",
    selectGradeHint: "درجه کیفیت را انتخاب کنید",
    selectSupplierHint: "برای مشاهده رسانه و موقعیت بارگیری، تامین‌کننده را انتخاب کنید",
    supplierOfTotal: "تامین‌کننده {index} از {total}",
    supplierSelected: "انتخاب‌شده",
    suppliersCount: "{count} تامین‌کننده",
    suppliersForGrade: "{count} تامین‌کننده برای «{grade}»",
    viewGradeOffer: "مشاهده",
    gradeMediaSection: "رسانه این درجه",
    gradeMediaDesc: "عکس و فیلم‌های زیر مخصوص همین درجه کیفیت است",
    gradeMediaBadge: "رسانه این درجه",
    gradeMediaHeroHint: "عکس و فیلم هر درجه در بخش پیشنهادها نمایش داده می‌شود",
    noGradeMedia: "برای این درجه هنوز عکس یا فیلم ثبت نشده است",
    orderQuantityLabel: "مقدار سفارش",
    orderMaxHint: "حداکثر {unit} {quantity}",
    addToCartAction: "افزودن به سبد",
    productInfoSection: "اطلاعات پیشنهاد",
    orderSectionTitle: "ثبت سفارش",
    priceSectionTitle: "قیمت فروش",
    stockSectionTitle: "موجودی این بار",
    lotGradeLabel: "درجه کیفیت",
    lotStatusLabel: "وضعیت بار",
    stockAvailableLabel: "قابل سفارش",
    stockTotalLabel: "کل بار",
    stockReservedLabel: "رزرو شده",
    stockInLotsCount: "در {count} بار",
    stockLotsBreakdownHint: "موجودی قابل سفارش به تفکیک بار",
    mediaOfTotal: "{current} از {total}",
    viewAllMedia: "گالری",
    viewGallery: "مشاهده گالری",
    prevMedia: "رسانه قبلی",
    swipeMediaHint: "برای دیدن عکس و فیلم بکشید",
    tapMediaHint: "برای بزرگ‌نمایی ضربه بزنید",
    zoomIn: "بزرگ‌نمایی",
    zoomOut: "کوچک‌نمایی",
    reserved: "رزرو شده",
    availableToOffer: "قابل عرضه",
    grade: "درجه",
    total: "کل",
    lotsCount: "تعداد بار",
    availableProductsTitle: "محصولات موجود",
    media: "رسانه",
    price: "قیمت",
    minimumOrder: "حداقل سفارش",
    status: "وضعیت",
    attributes: "ویژگی‌ها",
    productDescriptionTitle: "درباره محصول",
    lotDescriptionTitle: "توضیحات تامین‌کننده",
    technicalSpecsTitle: "مشخصات فنی و بسته‌بندی",
    locationSectionTitle: "موقعیت",
    locationOnMap: "موقعیت روی نقشه",
    loadingLocationDefault: "محل بارگیری",
    navigateWith: "مسیریابی و اشتراک‌گذاری",
    openInGoogleMaps: "گوگل مپ",
    openInNeshan: "نشان",
    openInBalad: "بلد",
    openInWaze: "Waze",
    supplier: "تامین‌کننده",
    request: "درخواست",
    steppedPricing: "قیمت پلکانی",
    notSet: "—",
    fixedPrice: "قیمت ثابت",
    priceNotSet: "قیمت تعیین نشده",
    currencyToman: "تومان",
    moreAttributes: "+{count} ویژگی دیگر",
    orderRequest: "درخواست سفارش",
    invalidQuantity: "مقدار نامعتبر است",
    order: "سفارش",
    loading: "در حال بارگذاری...",
    noMediaToShow: "موردی برای نمایش وجود ندارد.",
    images: "تصاویر",
    videos: "ویدیوها",
    productMedia: "رسانه‌های محصول",
    productLabelPlural: "محصولات",
    view: "مشاهده",
    youHaveInCart: "شما هم‌اکنون {quantity} {unit} از این محصول را در سبد دارید.",
    viewCart: "مشاهده سبد خرید",
    orderAdded: "به بار اضافه شد.",
    closeMenu: "بستن منو",
    stockLegendAriaLabel: "راهنمای رنگ موجودی",
    catalogGuidePanelAriaLabel: "راهنمای دسته و محصول و رنگ کارت‌ها",
    stockLegendShortTitle: "رنگ‌بندی کارت‌ها",
    openGuideHelp: "مشاهده راهنما",
    guide: "راهنما",
    messages: "پیام‌ها",
    newChat: "گفتگوی جدید",
    newConversation: "شروع گفتگوی جدید",
    searchUserPlaceholder: "جستجوی نام یا موبایل…",
    noUsersFound: "کاربری یافت نشد",
    noConversations: "هنوز گفتگویی ندارید",
    selectConversation: "یک گفتگو انتخاب کنید یا گفتگوی جدید بسازید",
    startChat: "شروع گفتگو",
    typeMessage: "پیام خود را بنویسید…",
    send: "ارسال",
    sendImage: "ارسال تصویر",
    read: "خوانده شده",
    back: "بازگشت",
    closeGuide: "بستن",
    stockLegendTitle: "رنگ کارت‌ها بر اساس میزان موجودی (کیلوگرم) است:",
    stockEmpty: "بدون موجودی",
    stockEmptyRange: "۰ کیلوگرم",
    stockLow: "موجودی کم",
    stockLowRange: "زیر ۵ تن",
    stockMedium: "موجودی متوسط",
    stockMediumRange: "۵ تا ۲۰ تن",
    stockHigh: "موجودی زیاد",
    stockHighRange: "بالای ۲۰ تن",
    categoryProductGuideTitle: "تفاوت دسته و محصول",
    categoryProductGuideIntro: "کنار هر مورد در کارت‌ها، یکی از این دو برچسب نمایش داده می‌شود:",
    categoryProductGuideCategory:
      "گروهی که هنوز زیرمجموعه یا انواع بیشتری دارد و برای انتخاب کالای نهایی باید مرحلهٔ بعد را باز کنید.",
    categoryProductGuideProduct:
      "کالای نهایی و قابل سفارش؛ می‌توانید مستقیماً از صفحهٔ همان مورد درخواست خود را ثبت کنید.",
    categoryProductGuideCategoryShort: "وارد زیر دسته شوید",
    categoryProductGuideProductShort: "کالای نهایی قابل سفارش",
  },
  en: {
    siteName: "Zareoon",
    siteTagline: "A trusted bridge between production and consumption",
    siteIntro: "Zareoon is an online marketplace for various products, connecting producers, suppliers, and buyers directly.",
    cart: "Cart",
    language: "Language",
    selectLanguage: "Select language",
    dashboard: "Dashboard",
    loginRegister: "Login / Register",
    logout: "Logout",
    account: "Account",
    zareoonMe: "My Zareoon",
    myPublicPage: "My public page",
    myProducts: "My products",
    addProduct: "Add product",
    addNewProduct: "Add new product",
    editProfile: "Edit profile",
    customerOrders: "Customer orders",
    accountPageSubtitle: "Manage your personal details, contact information, and account security.",
    firstName: "First name",
    lastName: "Last name",
    fatherName: "Father's name",
    nationalId: "National ID number",
    address: "Address",
    postalCode: "Postal code",
    email: "Email",
    mobile: "Mobile",
    phone: "Phone",
    currentPassword: "Current password",
    newPassword: "New password",
    confirmPassword: "Confirm new password",
    saveChanges: "Save changes",
    saving: "Saving...",
    profileUpdated: "Your information was saved successfully.",
    profileUpdateFailed: "Could not save your information.",
    personalInfo: "Personal information",
    contactInfo: "Contact information",
    security: "Account security",
    changePasswordHint: "Fill in the fields below only if you want to change your password.",
    readOnlyField: "Read only",
    changePhoto: "Change photo",
    removePhoto: "Remove photo",
    uploadingPhoto: "Uploading...",
    photoUploadSuccess: "Profile photo saved.",
    photoUploadFailed: "Could not upload photo.",
    photoRemoveSuccess: "Profile photo removed.",
    photoHint: "PNG, JPG or WEBP — max 10 MB",
    changePassword: "Change password",
    accountTabDocuments: "Documents",
    accountTabMyFiles: "My files",
    accountDocumentsHint: "Upload identity documents and required files.",
    noFilesUploaded: "You have not uploaded any files yet.",
    download: "Download",
    allRightsReserved: "All rights reserved for Zareoon",
    home: "Home",
    search: "Search",
    products: "Products",
    inventory: "Inventory",
    orders: "Orders",
    login: "Login",
    profile: "Profile",
    searchPlaceholder: "Search products and categories...",
    productsAvailable: "Available Products",
    latestAvailableOnZareoon: "Latest Available Products on Zareoon",
    latestAvailableInCategory: "Latest available products in this category",
    latestAvailableInParent: "Latest available products in {name}",
    latestAvailableShort: "Latest stock",
    showAllCategories: "All Categories",
    browseByCategory: "Browse categories",
    browseByCategoryHint: "Choose a category above to browse subcategories and products step by step.",
    nothingFound: "Nothing found",
    product: "Product",
    category: "Category",
    totalAvailableStock: "Total available",
    supplySource: "Supply source",
    supplyCountry: "Supply country",
    supplyCity: "City (optional)",
    noProductsWithStock: "No products with registered stock.",
    viewAllCategories: "View all categories",
    adBadge: "Inspection & Quality Control",
    adSponsoredLabel: "Advertisement",
    adBrandName: "Arya Foolad Gharn",
    openAdDetails: "View advertisement",
    adTitle: "Make sure of your goods quality before import or export.",
    adDescription:
      "Arya Foolad Gharn reduces your trade risks and ensures compliance with required standards through cargo inspection, quality control, raw material inspection, industrial equipment inspection, and valid certification services.",
    adItem1: "Imported and exported goods inspection",
    adItem2: "Quality control (QC)",
    adItem3: "Raw materials and production inspection",
    adItem4: "Technical reports and inspection certificates",
    adFooter: "Arya Foolad Gharn Engineering Inspection Company; your trusted partner in international trade.",
    enterSite: "Click to visit website",
    lcBadge: "Letter of Credit",
    openLcDetails: "View details",
    lcTitle: "Specialized Letter of Credit (LC) Services",
    lcDescription:
      "If you need an LC for import or export, entrust us with every stage of opening, tracking, and executing it with confidence.",
    lcItem1: "LC opening",
    lcItem2: "Process tracking",
    lcItem3: "Bank and counterparty coordination",
    lcItem4: "Import and export advisory",
    lcFooter: "Your trusted partner in international trade.",
    lcRequestCta: "Request LC",
    lcFormTitle: "Letter of Credit (LC) Request Form",
    lcFormFullName: "Full name",
    lcFormPhone: "Phone number",
    lcFormEmail: "Email",
    lcFormCompany: "Company name",
    lcFormTradeType: "Trade type",
    lcFormTradeImport: "Import",
    lcFormTradeExport: "Export",
    lcFormTradeBoth: "Import and export",
    lcFormProductDescription: "Goods / services description",
    lcFormEstimatedAmount: "Estimated amount",
    lcFormCurrency: "Currency",
    lcFormBankName: "Bank name (if any)",
    lcFormNotes: "Additional notes",
    lcFormRequiredError: "Full name and phone are required",
    lcFormSubmitError: "Failed to submit request. Please try again.",
    lcFormSubmitting: "Submitting...",
    lcFormSuccessTitle: "Your request has been submitted",
    lcFormSuccessMessage: "Zareoon specialists will contact you as soon as possible.",
    serviceRequestCta: "Submit request",
    serviceRequestFormTitle: "{service} — request form",
    srFormOriginCountry: "Origin country",
    srFormDestinationCountry: "Destination country",
    srFormIncoterm: "Incoterm",
    srFormTransportMode: "Transport mode",
    srFormTransportSea: "Sea",
    srFormTransportAir: "Air",
    srFormTransportRoad: "Road",
    srFormTransportRail: "Rail",
    srFormOriginLocation: "Origin",
    srFormDestinationLocation: "Destination",
    srFormCargoWeight: "Cargo weight / volume",
    srFormPortOfEntry: "Port / customs office",
    srFormHsCode: "HS code",
    srFormDeclarationType: "Declaration type",
    srFormPaymentMethod: "Payment method",
    srFormPaymentLc: "Letter of Credit (LC)",
    srFormPaymentTt: "Telegraphic transfer (TT)",
    srFormPaymentCollection: "Documentary collection",
    srFormPaymentOther: "Other",
    srFormBankName: "Bank name",
    srFormInspectionType: "Inspection type",
    srFormStandardRequired: "Required standard",
    srFormInspectionLocation: "Inspection location",
    srFormInsuranceCoverage: "Insurance coverage",
    srFormCargoValue: "Cargo value",
    srFormRouteDescription: "Route description",
    srFormTargetMarket: "Target market",
    srFormConsultationTopic: "Consultation topic",
    srFormRequiredDocuments: "Required documents",
    srFormShipmentDeadline: "Shipment deadline",
    serviceRequestCta: "Submit request",
    serviceRequestFormTitle: "Request form — {service}",
    srFormOriginCountry: "Origin country",
    srFormDestinationCountry: "Destination country",
    srFormIncoterm: "Incoterm",
    srFormTransportMode: "Transport mode",
    srFormTransportSea: "Sea",
    srFormTransportAir: "Air",
    srFormTransportRoad: "Road",
    srFormTransportRail: "Rail",
    srFormOriginLocation: "Origin",
    srFormDestinationLocation: "Destination",
    srFormCargoWeight: "Cargo weight / volume",
    srFormPortOfEntry: "Port / customs office",
    srFormHsCode: "HS code",
    srFormDeclarationType: "Declaration type",
    srFormPaymentMethod: "Payment method",
    srFormPaymentLc: "Letter of Credit (LC)",
    srFormPaymentTt: "Telegraphic transfer (TT)",
    srFormPaymentCollection: "Documentary collection",
    srFormPaymentOther: "Other",
    srFormBankName: "Bank name",
    srFormInspectionType: "Inspection type",
    srFormStandardRequired: "Required standard",
    srFormInspectionLocation: "Inspection location",
    srFormInsuranceCoverage: "Insurance coverage",
    srFormCargoValue: "Cargo value",
    srFormRouteDescription: "Route description",
    srFormTargetMarket: "Target market",
    srFormConsultationTopic: "Consultation topic",
    srFormRequiredDocuments: "Required documents",
    srFormShipmentDeadline: "Shipment deadline",
    agriculturalProducts: "Products & categories",
    agriculturalProductsDesc: "A complete range of products and goods from various suppliers",
    downloadCatalogPdf: "Download catalog PDF",
    downloadSupplierCatalogPdf: "Download this supplier's catalog",
    productCategories: "Product Categories",
    categoriesShort: "Categories",
    back: "Back",
    subcategoriesAndProducts: "Subcategories and products",
    subcategories: "Subcategories",
    subcategoriesOfParent: "Subcategories of {name}",
    showOnlyWithStock: "In stock only",
    groupByCategory: "Group by category",
    viewAll: "View all",
    noItemsRegistered: "No items registered",
    noCategoryRegistered: "No categories have been registered.",
    pleaseVisitLater: "Please check back later.",
    requestedItemsInCart: "Request submitted - {count} items are currently in your cargo list",
    viewCartAndSubmit: "View cart and place order",
    cartReservationNote: "Placing your order does not automatically reserve stock; the Zareoon team will contact you to confirm and coordinate delivery.",
    supportContact: "Support",
    pleaseLoginFirst: "Please log in first",
    statusOnField: "At source",
    statusHarvested: "Available",
    statusReserved: "Reserved",
    statusSold: "Sold",
    qualityExport: "Export",
    qualityGrade1: "Grade 1",
    qualityGrade2: "Grade 2",
    qualityGrade3: "Grade 3",
    qualityWaste: "Waste",
    qualityOther: "Other",
    mainPage: "Home",
    orderable: "Orderable",
    unitLabel: "Unit",
    nonOrderableCategoryRole: "Not orderable (category role)",
    totalStockStatus: "Overall stock status",
    totalStock: "Total stock",
    totalProducts: "Products count",
    productsWithStock: "Products with stock",
    inventoryStatus: "Stock status",
    inventoryOverviewDesc: "Total stock for this product and how much you can order",
    inventoryOverviewShort: "Per-grade details are in the offers section",
    gradeBreakdownTitle: "Stock by grade",
    gradeBreakdownDesc: "Compare available stock for each quality grade",
    offersSectionTitle: "Orderable offers",
    offersSectionDesc: "Enter a quantity and add it to your cart",
    selectGradeHint: "Select a quality grade",
    selectSupplierHint: "Select a supplier to view their media and loading location",
    supplierOfTotal: "Supplier {index} of {total}",
    supplierSelected: "Selected",
    suppliersCount: "{count} suppliers",
    suppliersForGrade: "{count} suppliers for “{grade}”",
    viewGradeOffer: "View",
    gradeMediaSection: "Media for this grade",
    gradeMediaDesc: "Photos and videos below belong to this quality grade only",
    gradeMediaBadge: "This grade's media",
    gradeMediaHeroHint: "Each grade's photos and videos are shown in the offers section",
    noGradeMedia: "No photos or videos uploaded for this grade yet",
    orderQuantityLabel: "Order quantity",
    orderMaxHint: "Max {quantity} {unit}",
    addToCartAction: "Add to cart",
    productInfoSection: "Offer details",
    orderSectionTitle: "Place order",
    priceSectionTitle: "Selling price",
    stockSectionTitle: "Lot stock",
    lotGradeLabel: "Quality grade",
    lotStatusLabel: "Lot status",
    stockAvailableLabel: "Available to order",
    stockTotalLabel: "Total lot",
    stockReservedLabel: "Reserved",
    stockInLotsCount: "in {count} lots",
    stockLotsBreakdownHint: "Available stock by lot",
    mediaOfTotal: "{current} of {total}",
    viewAllMedia: "Gallery",
    viewGallery: "View gallery",
    prevMedia: "Previous",
    swipeMediaHint: "Swipe to view photos and videos",
    tapMediaHint: "Tap to enlarge",
    zoomIn: "Zoom in",
    zoomOut: "Zoom out",
    reserved: "Reserved",
    availableToOffer: "Available",
    grade: "Grade",
    total: "Total",
    lotsCount: "Lots",
    availableProductsTitle: "Available Lots",
    media: "Media",
    price: "Price",
    minimumOrder: "Minimum order",
    status: "Status",
    attributes: "Attributes",
    productDescriptionTitle: "About this product",
    lotDescriptionTitle: "Supplier notes",
    technicalSpecsTitle: "Technical specs & packaging",
    locationSectionTitle: "Location",
    locationOnMap: "Location on map",
    loadingLocationDefault: "Loading point",
    navigateWith: "Navigate & share",
    openInGoogleMaps: "Google Maps",
    openInNeshan: "Neshan",
    openInBalad: "Balad",
    openInWaze: "Waze",
    supplier: "Supplier",
    request: "Request",
    steppedPricing: "Tiered pricing",
    notSet: "—",
    fixedPrice: "Fixed price",
    priceNotSet: "Price not set",
    currencyToman: "Toman",
    moreAttributes: "+{count} more attributes",
    orderRequest: "Order request",
    invalidQuantity: "Invalid quantity",
    order: "Order",
    loading: "Loading...",
    noMediaToShow: "There is no media to display.",
    images: "Images",
    videos: "Videos",
    productMedia: "Product media",
    productLabelPlural: "Products",
    view: "View",
    youHaveInCart: "You currently have {quantity} {unit} of this product in your cart.",
    viewCart: "View cart",
    orderAdded: "Added to cargo list.",
    closeMenu: "Close menu",
    stockLegendAriaLabel: "Stock color guide",
    catalogGuidePanelAriaLabel: "Category, product and card color guide",
    stockLegendShortTitle: "Card colors",
    openGuideHelp: "View guide",
    guide: "Guide",
    messages: "Messages",
    newChat: "New chat",
    newConversation: "Start new conversation",
    searchUserPlaceholder: "Search name or mobile…",
    noUsersFound: "No users found",
    noConversations: "No conversations yet",
    selectConversation: "Select a conversation or start a new one",
    startChat: "Start chatting",
    typeMessage: "Type your message…",
    send: "Send",
    sendImage: "Send image",
    read: "Read",
    back: "Back",
    closeGuide: "Close",
    stockLegendTitle: "Card colors are based on available stock (kilograms):",
    stockEmpty: "Out of stock",
    stockEmptyRange: "0 kg",
    stockLow: "Low stock",
    stockLowRange: "Below 5 tons",
    stockMedium: "Medium stock",
    stockMediumRange: "5 to 20 tons",
    stockHigh: "High stock",
    stockHighRange: "Above 20 tons",
    categoryProductGuideTitle: "Categories and products",
    categoryProductGuideIntro: "Each item in a card is marked with one of these labels:",
    categoryProductGuideCategory:
      "A group that still has subcategories or varieties — open the next level to reach the final item.",
    categoryProductGuideProduct:
      "The final orderable item — submit your request directly from that page.",
    categoryProductGuideCategoryShort: "Enter a subcategory",
    categoryProductGuideProductShort: "Final orderable item",
  },
  ru: {
    siteName: "Zareoon",
    siteTagline: "Надежная платформа между производством и потреблением",
    siteIntro: "Zareoon - онлайн-площадка для торговли различными товарами, связывающая производителей, поставщиков и покупателей.",
    cart: "Корзина",
    language: "Язык",
    selectLanguage: "Выбор языка",
    dashboard: "Панель",
    loginRegister: "Вход / Регистрация",
    logout: "Выход",
    account: "Аккаунт",
    zareoonMe: "Мой Zareoon",
    myPublicPage: "Моя публичная страница",
    myProducts: "Мои товары",
    addProduct: "Добавить товар",
    addNewProduct: "Добавить новый товар",
    editProfile: "Редактировать профиль",
    customerOrders: "Заказы клиентов",
    accountPageSubtitle: "Управляйте личными данными, контактами и безопасностью аккаунта.",
    firstName: "Имя",
    lastName: "Фамилия",
    fatherName: "Отчество",
    nationalId: "Номер удостоверения",
    address: "Адрес",
    postalCode: "Почтовый индекс",
    email: "Email",
    mobile: "Мобильный",
    phone: "Телефон",
    currentPassword: "Текущий пароль",
    newPassword: "Новый пароль",
    confirmPassword: "Подтверждение пароля",
    saveChanges: "Сохранить",
    saving: "Сохранение...",
    profileUpdated: "Данные успешно сохранены.",
    profileUpdateFailed: "Не удалось сохранить данные.",
    personalInfo: "Личные данные",
    contactInfo: "Контактная информация",
    security: "Безопасность",
    changePasswordHint: "Заполните поля ниже только если хотите сменить пароль.",
    readOnlyField: "Только чтение",
    changePhoto: "Сменить фото",
    removePhoto: "Удалить фото",
    uploadingPhoto: "Загрузка...",
    photoUploadSuccess: "Фото профиля сохранено.",
    photoUploadFailed: "Не удалось загрузить фото.",
    photoRemoveSuccess: "Фото профиля удалено.",
    photoHint: "PNG, JPG или WEBP — до 10 МБ",
    changePassword: "Сменить пароль",
    accountTabDocuments: "Документы",
    accountTabMyFiles: "Мои файлы",
    accountDocumentsHint: "Загрузите удостоверение личности и необходимые документы.",
    noFilesUploaded: "Вы ещё не загрузили файлы.",
    download: "Скачать",
    allRightsReserved: "Все права на этот сайт принадлежат Zareoon",
    home: "Главная",
    search: "Поиск",
    products: "Товары",
    inventory: "Запасы",
    orders: "Заказы",
    login: "Вход",
    profile: "Профиль",
    searchPlaceholder: "Поиск товаров и категорий...",
    productsAvailable: "Товары в наличии",
    latestAvailableOnZareoon: "Новейшие товары в наличии на Zareoon",
    latestAvailableInCategory: "Новейшие товары в наличии в этой категории",
    latestAvailableInParent: "Новейшие товары в наличии в {name}",
    latestAvailableShort: "Новинки",
    showAllCategories: "Все категории",
    browseByCategory: "Обзор категорий",
    browseByCategoryHint: "Выберите категорию выше, чтобы пошагово просматривать подкатегории и товары.",
    nothingFound: "Ничего не найдено",
    product: "Товар",
    category: "Категория",
    totalAvailableStock: "Всего в наличии",
    supplySource: "Источник поставки",
    supplyCountry: "Страна поставки",
    supplyCity: "Город (необязательно)",
    noProductsWithStock: "Нет товаров с зарегистрированным наличием.",
    viewAllCategories: "Смотреть все категории",
    adBadge: "Инспекция и контроль качества",
    adSponsoredLabel: "Реклама",
    adBrandName: "Arya Foolad Gharn",
    openAdDetails: "Посмотреть рекламу",
    adTitle: "Убедитесь в качестве товара до импорта или экспорта.",
    adDescription:
      "Arya Foolad Gharn снижает риски ваших торговых сделок и обеспечивает соответствие стандартам, предоставляя инспекцию товаров, контроль качества, проверку сырья, промышленного оборудования и выдачу официальных сертификатов.",
    adItem1: "Инспекция импортных и экспортных грузов",
    adItem2: "Контроль качества (QC)",
    adItem3: "Проверка сырья и готовой продукции",
    adItem4: "Технические отчеты и сертификаты инспекции",
    adFooter: "Инженерно-инспекционная компания Arya Foolad Gharn — ваш надежный партнер в международной торговле.",
    enterSite: "Нажмите, чтобы перейти на сайт",
    lcBadge: "Аккредитив",
    openLcDetails: "Подробнее",
    lcTitle: "Специализированные услуги по аккредитиву (LC)",
    lcDescription:
      "Если вам нужен LC для импорта или экспорта, доверьте нам все этапы открытия, сопровождения и исполнения с полной уверенностью.",
    lcItem1: "Открытие аккредитива (LC)",
    lcItem2: "Сопровождение процесса",
    lcItem3: "Координация с банком и контрагентами",
    lcItem4: "Консультации по импорту и экспорту",
    lcFooter: "Ваш надежный партнер в международной торговле.",
    lcRequestCta: "Запрос LC",
    lcFormTitle: "Форма запроса аккредитива (LC)",
    lcFormFullName: "ФИО",
    lcFormPhone: "Телефон",
    lcFormEmail: "Email",
    lcFormCompany: "Название компании",
    lcFormTradeType: "Тип сделки",
    lcFormTradeImport: "Импорт",
    lcFormTradeExport: "Экспорт",
    lcFormTradeBoth: "Импорт и экспорт",
    lcFormProductDescription: "Описание товара / услуги",
    lcFormEstimatedAmount: "Примерная сумма",
    lcFormCurrency: "Валюта",
    lcFormBankName: "Банк (если есть)",
    lcFormNotes: "Дополнительные примечания",
    lcFormRequiredError: "Укажите имя и телефон",
    lcFormSubmitError: "Не удалось отправить запрос. Попробуйте снова.",
    lcFormSubmitting: "Отправка...",
    lcFormSuccessTitle: "Запрос отправлен",
    lcFormSuccessMessage: "Специалисты Zareoon свяжутся с вами в ближайшее время.",
    serviceRequestCta: "Отправить запрос",
    serviceRequestFormTitle: "Форма запроса: {service}",
    srFormOriginCountry: "Страна отправления",
    srFormDestinationCountry: "Страна назначения",
    srFormIncoterm: "Инкотермс",
    srFormTransportMode: "Способ перевозки",
    srFormTransportSea: "Морской",
    srFormTransportAir: "Воздушный",
    srFormTransportRoad: "Автомобильный",
    srFormTransportRail: "Железнодорожный",
    srFormOriginLocation: "Пункт отправления",
    srFormDestinationLocation: "Пункт назначения",
    srFormCargoWeight: "Вес / объём груза",
    srFormPortOfEntry: "Порт / таможня",
    srFormHsCode: "Код ТН ВЭД (HS)",
    srFormDeclarationType: "Тип декларации",
    srFormPaymentMethod: "Способ оплаты",
    srFormPaymentLc: "Аккредитив (LC)",
    srFormPaymentTt: "Телеграфный перевод (TT)",
    srFormPaymentCollection: "Инкассо",
    srFormPaymentOther: "Другое",
    srFormBankName: "Банк",
    srFormInspectionType: "Тип инспекции",
    srFormStandardRequired: "Требуемый стандарт",
    srFormInspectionLocation: "Место инспекции",
    srFormInsuranceCoverage: "Тип страхового покрытия",
    srFormCargoValue: "Стоимость груза",
    srFormRouteDescription: "Маршрут",
    srFormTargetMarket: "Целевой рынок",
    srFormConsultationTopic: "Тема консультации",
    srFormRequiredDocuments: "Необходимые документы",
    srFormShipmentDeadline: "Срок отгрузки",
    agriculturalProducts: "Товары и категории",
    agriculturalProductsDesc: "Полный ассортимент товаров от разных поставщиков",
    downloadCatalogPdf: "Скачать PDF каталога",
    downloadSupplierCatalogPdf: "Скачать каталог этого поставщика",
    productCategories: "Категории товаров",
    categoriesShort: "Категории",
    back: "Назад",
    subcategoriesAndProducts: "Подкатегории и товары",
    subcategories: "Подкатегории",
    subcategoriesOfParent: "Подкатегории {name}",
    showOnlyWithStock: "Только в наличии",
    groupByCategory: "По категориям",
    viewAll: "Смотреть все",
    noItemsRegistered: "Ничего не зарегистрировано",
    noCategoryRegistered: "Категории не зарегистрированы.",
    pleaseVisitLater: "Пожалуйста, зайдите позже.",
    requestedItemsInCart: "Запрос отправлен — {count} позиций сейчас находятся в вашем списке груза",
    viewCartAndSubmit: "Открыть груз и отправить",
    cartReservationNote: "Отправка груза не резервирует его автоматически, но с клиентом свяжутся для подтверждения резерва.",
    supportContact: "Поддержка",
    pleaseLoginFirst: "Сначала войдите",
    statusOnField: "На месте поставки",
    statusHarvested: "Доступно",
    statusReserved: "Зарезервировано",
    statusSold: "Продано",
    qualityExport: "Экспорт",
    qualityGrade1: "1 сорт",
    qualityGrade2: "2 сорт",
    qualityGrade3: "3 сорт",
    qualityWaste: "Отходы",
    qualityOther: "Другое",
    mainPage: "Главная",
    orderable: "Можно заказать",
    unitLabel: "Ед.",
    nonOrderableCategoryRole: "Недоступно для заказа (категория)",
    totalStockStatus: "Общее состояние запасов",
    totalStock: "Общий запас",
    totalProducts: "Количество товаров",
    productsWithStock: "Товары в наличии",
    inventoryStatus: "Состояние запасов",
    inventoryOverviewDesc: "Общий запас товара и доступное для заказа количество",
    inventoryOverviewShort: "Детали по сортам — в разделе предложений",
    gradeBreakdownTitle: "Запас по сортам",
    gradeBreakdownDesc: "Сравнение доступного запаса по каждому сорту",
    offersSectionTitle: "Доступные предложения",
    offersSectionDesc: "Введите количество и добавьте в корзину",
    selectGradeHint: "Выберите сорт",
    selectSupplierHint: "Выберите поставщика для просмотра медиа и места погрузки",
    supplierOfTotal: "Поставщик {index} из {total}",
    supplierSelected: "Выбран",
    suppliersCount: "{count} поставщиков",
    suppliersForGrade: "{count} поставщиков для «{grade}»",
    viewGradeOffer: "Смотреть",
    gradeMediaSection: "Медиа этого сорта",
    gradeMediaDesc: "Фото и видео ниже относятся только к этому сорту",
    gradeMediaBadge: "Медиа сорта",
    gradeMediaHeroHint: "Фото и видео каждого сорта показаны в разделе предложений",
    noGradeMedia: "Для этого сорта пока нет фото или видео",
    orderQuantityLabel: "Количество заказа",
    orderMaxHint: "Макс. {quantity} {unit}",
    addToCartAction: "В корзину",
    productInfoSection: "Детали предложения",
    orderSectionTitle: "Оформить заказ",
    priceSectionTitle: "Цена продажи",
    stockSectionTitle: "Запас партии",
    lotGradeLabel: "Сорт",
    lotStatusLabel: "Статус партии",
    stockAvailableLabel: "Доступно для заказа",
    stockTotalLabel: "Всего в партии",
    stockReservedLabel: "Зарезервировано",
    stockInLotsCount: "в {count} партиях",
    stockLotsBreakdownHint: "Доступный остаток по партиям",
    mediaOfTotal: "{current} из {total}",
    viewAllMedia: "Галерея",
    viewGallery: "Смотреть галерею",
    prevMedia: "Назад",
    swipeMediaHint: "Проведите для просмотра фото и видео",
    tapMediaHint: "Нажмите для увеличения",
    zoomIn: "Увеличить",
    zoomOut: "Уменьшить",
    reserved: "Зарезервировано",
    availableToOffer: "Доступно",
    grade: "Сорт",
    total: "Всего",
    lotsCount: "Партии",
    availableProductsTitle: "Доступные партии",
    media: "Медиа",
    price: "Цена",
    minimumOrder: "Мин. заказ",
    status: "Статус",
    attributes: "Характеристики",
    productDescriptionTitle: "О продукте",
    lotDescriptionTitle: "Примечания поставщика",
    technicalSpecsTitle: "Технические характеристики и упаковка",
    locationSectionTitle: "Местоположение",
    locationOnMap: "На карте",
    loadingLocationDefault: "Пункт погрузки",
    navigateWith: "Маршрут и поделиться",
    openInGoogleMaps: "Google Maps",
    openInNeshan: "Neshan",
    openInBalad: "Balad",
    openInWaze: "Waze",
    supplier: "Поставщик",
    request: "Запрос",
    steppedPricing: "Ступенчатая цена",
    notSet: "—",
    fixedPrice: "Фиксированная цена",
    priceNotSet: "Цена не указана",
    currencyToman: "Томан",
    moreAttributes: "+{count} атрибутов",
    orderRequest: "Запрос заказа",
    invalidQuantity: "Неверное количество",
    order: "Заказать",
    loading: "Загрузка...",
    noMediaToShow: "Нет медиа для отображения.",
    images: "Изображения",
    videos: "Видео",
    productMedia: "Медиа товара",
    productLabelPlural: "Товары",
    view: "Открыть",
    youHaveInCart: "Сейчас у вас в корзине {quantity} {unit} этого товара.",
    viewCart: "Открыть корзину",
    orderAdded: "Добавлено в список груза.",
    closeMenu: "Закрыть меню",
    stockLegendAriaLabel: "Справочник цветов запасов",
    catalogGuidePanelAriaLabel: "Справочник категорий, товаров и цветов карточек",
    stockLegendShortTitle: "Цвета карточек",
    openGuideHelp: "Открыть справочник",
    guide: "Справка",
    messages: "Сообщения",
    newChat: "Новый чат",
    newConversation: "Начать новый диалог",
    searchUserPlaceholder: "Поиск по имени или телефону…",
    noUsersFound: "Пользователи не найдены",
    noConversations: "Пока нет диалогов",
    selectConversation: "Выберите диалог или начните новый",
    startChat: "Начать общение",
    typeMessage: "Введите сообщение…",
    send: "Отправить",
    sendImage: "Отправить фото",
    read: "Прочитано",
    back: "Назад",
    closeGuide: "Закрыть",
    stockLegendTitle: "Цвет карточек зависит от доступного запаса (в килограммах):",
    stockEmpty: "Нет в наличии",
    stockEmptyRange: "0 кг",
    stockLow: "Низкий запас",
    stockLowRange: "Менее 5 тонн",
    stockMedium: "Средний запас",
    stockMediumRange: "От 5 до 20 тонн",
    stockHigh: "Высокий запас",
    stockHighRange: "Более 20 тонн",
    categoryProductGuideTitle: "Категория и товар",
    categoryProductGuideIntro: "Рядом с каждым пунктом в карточке указана одна из этих меток:",
    categoryProductGuideCategory:
      "Группа с подкатегориями или разными видами — откройте следующий уровень, чтобы выбрать конечный товар.",
    categoryProductGuideProduct:
      "Конечный товар, доступный для заказа — оформите запрос прямо на его странице.",
    categoryProductGuideCategoryShort: "Перейдите в подкатегорию",
    categoryProductGuideProductShort: "Конечный товар для заказа",
  },
};

const siteIntroByLang = {
  fa: translations.fa.siteIntro,
  en: translations.en.siteIntro,
  ru: translations.ru.siteIntro,
};

export { siteIntroByLang };

const LanguageContext = createContext(null);

function interpolate(template, values = {}) {
  return Object.entries(values).reduce(
    (acc, [key, value]) => acc.replaceAll(`{${key}}`, value),
    template
  );
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState("fa");
  const [isHydrated, setIsHydrated] = useState(false);

  useEffect(() => {
    const saved = window.localStorage.getItem(STORAGE_KEY);
    if (saved && ["fa", "en", "ru"].includes(saved)) {
      setLanguage(saved);
    } else if (saved === "ar") {
      setLanguage("fa");
    }
    setIsHydrated(true);
  }, []);

  useEffect(() => {
    if (!isHydrated) return;
    window.localStorage.setItem(STORAGE_KEY, language);
    document.documentElement.lang = language;
    document.documentElement.dir = language === "fa" ? "rtl" : "ltr";
  }, [language, isHydrated]);

  const value = useMemo(() => {
    const dict = translations[language] && Object.keys(translations[language]).length
      ? translations[language]
      : translations.fa;
    return {
      language,
      setLanguage,
      isHydrated,
      isRTL: language === "fa",
      t: (key, values) => {
        const text = dict[key] ?? translations.fa[key] ?? key;
        return values ? interpolate(text, values) : text;
      },
      siteIntroByLang,
    };
  }, [language, isHydrated]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}
